name: Operator
description: Add an operator
title: '[Operation OPERATION_NAME] OPERATOR_NAME'
labels: ['enhancement']
body:
  - type: input
    id: name
    attributes:
      label: Name/Nickname
      description: 'Readable name of the operator.'
      placeholder: 'ex: Sledge, Jäger'
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: Role
      description: 'Role of the operator.'
      options:
        - Attacker
        - Defender
    validations:
      required: true
  - type: input
    id: org
    attributes:
      label: Organization
      description: 'Operator organisation name.'
      placeholder: 'ex: FBI, SWAT'
    validations:
      required: true
  - type: input
    id: squad
    attributes:
      label: Squad
      description: 'Operator squad name.'
      placeholder: 'ex: Nighthaven'
    validations:
      required: true
  - type: dropdown
    id: speed
    attributes:
      label: Speed
      description: 'Speed rating.'
      options:
        - 1
        - 2
        - 3
    validations:
      required: true
  - type: dropdown
    id: health
    attributes:
      label: Health
      description: 'Health Rating.'
      options:
        - 1
        - 2
        - 3
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficilty
      description: 'Difficulty rating.'
      options:
        - 1
        - 2
        - 3
    validations:
      required: true
  - type: dropdown
    id: gender
    attributes:
      label: Gender
      description: 'm - Male, f - Female, o - Other, n - None/Not applicable, u - Unknown.'
      options:
        - 'm'
        - 'f'
        - 'o'
        - 'n'
        - 'u'
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Country
      description: 'Country of the operator as a ISO 3166-1 alpha-2 code (https://wikipedia.org/wiki/ISO_3166-1_alpha-2).'
      placeholder: 'ex: DE, SK'
    validations:
      required: true
  - type: input
    id: season
    attributes:
      label: Season
      description: 'Season shorthandle when the operator was first introduced to the game.'
      placeholder: 'ex: Y1S1'
    validations:
      required: true
  - type: input
    id: height
    attributes:
      label: Height
      description: 'Height of the operator, in cm.'
      placeholder: 'ex: 175'
    validations:
      required: true
  - type: input
    id: weight
    attributes:
      label: Weight
      description: 'Weight of the operator, in kg.'
      placeholder: 'ex: 75'
    validations:
      required: true
  - type: input
    id: real-name
    attributes:
      label: Real name
      description: 'Real name of the operator.'
      placeholder: 'Miles Campbell'
    validations:
      required: true
  - type: input
    id: birthplace
    attributes:
      label: Birthplace
      description: 'Birthplace of the operator, including the country.'
      placeholder: 'Sherman Oaks, U.S.A'
    validations:
      required: true
  # Can be add later
  # - type: input
  #   id: date-of-birth
  #   attributes:
  #     label: Date of birth
  #     description: 'Date of birth of the operator as a ISO 8601 (https://wikipedia.org/wiki/ISO_8601).'
  #     placeholder: 'ex: 1968-07-12'
  #   validations:
  #     required: true
  - type: textarea
    id: icon
    attributes:
      label: Icon
      description: 'Highiest resolution of operator icon you could find, in-game lossless screenshot, asset packs.'
      value: |
        <details>
        <summary>Expand</summary>


        Icon image goes here


        </details>
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Reference
      description: 'Sources of information filled above. Screenshots, urls.'
      value: |
        <details>
        <summary>Expand</summary>


        Media files goes here


        </details>
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
